// -*- jsonc -*-
{
  "height": 16,
  "tray": {
    "icon-size": 14
  },
  "clock": {
    "format-alt": "{:%a %Y-%m-%d %T}",
    "format": "{:%T}"
  },
  "modules-center": [
    "privacy",
    "systemd-failed-units",
  ],
  "modules-right": [
    "idle_inhibitor",
    "power-profiles-daemon",
    "pulseaudio",
    "bluetooth",
    "network",
    "cpu",
    "memory",
    "temperature",
    "backlight",
    "battery",
    "clock",
    "tray",
    "custom/notification"
  ],
  "custom/notification": {
    "tooltip": false,
    "format": "{icon}",
    "format-icons": {
      "notification": "<span foreground='red'><sup></sup></span>",
      "none": "",
      "dnd-notification": "<span foreground='red'><sup></sup></span>",
      "dnd-none": ""
    },
    "return-type": "json",
    "exec-if": "which swaync-client",
    "exec": "swaync-client -swb",
    "on-click": "swaync-client -t -sw",
    "on-click-right": "swaync-client -d -sw",
    "escape": true
  }
}

// Local Variables:
// indent-tabs-mode: nil
// js-indent-level: 2
// End:
