bindsym $mod+Return exec kitty-1
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec mako
exec swayidle -w lock "swaylock -f" before-sleep "loginctl lock-session" timeout 600 'swaymsg "output * dpms off"; loginctl lock-session' resume 'swaymsg "output * dpms on"'
# Lat/Lon for Aachen
exec wlsunset -l 50.8 -L 6.1

output * scale 2
output DP-1 pos 0 0
output HDMI-A-1 pos 1920 0
